export type Severity = 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL'
export type RiskLevel = 'LOW' | 'MEDIUM' | 'HIGH'
export type Result = 'SUCCESS' | 'FAILED' | 'PARTIAL'
export type IncidentStatus = 'INVESTIGATING' | 'APPROVAL_REQUIRED' | 'RESOLVED' | 'PARTIAL' | 'INSUFFICIENT_EVIDENCE'
export interface Incident { incident_id: string; service: string; severity: Severity; symptoms: string[]; environment: string; error_code?: string | null; error_message?: string | null; customer_id?: string | null; transaction_id?: string | null; job_id?: string | null; recent_change?: string | null }
export interface Outcome { outcome_id: string; incident_id: string; action: string; result: Result; tool_result?: Result | null; reprocessing_result?: Result | null; lesson_learned: string; risk_level: RiskLevel; verified: boolean; resolution_time_minutes?: number | null }
export interface IncidentMemory { incident: Incident; root_cause?: string | null; outcomes: Outcome[]; final_resolution?: string | null; final_outcome?: Result | null; source_filename?: string; chunk_refs?: string[] }
export interface IncidentListItem extends Incident { status: IncidentStatus; occurred_at: string }
export interface EvidenceItem { incident_id: string; similarity: number; root_cause?: string | null; outcomes: Outcome[] }
export interface IncidentWorkspace { incident: IncidentListItem; likely_root_cause: string; recommended_action: string; confidence: number; risk_level: RiskLevel; reasoning: string; investigation_method: 'deterministic_history_baseline' | 'llm_grounded' | 'deterministic_fallback'; model_name?: string; fallback_reason?: string; evidence: EvidenceItem[]; failed_actions_avoided: string[]; policy_status: 'ALLOWED' | 'HUMAN_APPROVAL_REQUIRED' | 'BLOCKED'; workflow_status: IncidentStatus; tool_acknowledgement?: Result; verification?: { service_healthy: boolean; operation_recovered: boolean; result: Result }; memory_stored: boolean }
export type UploadStage = 'uploading' | 'extracting' | 'validating' | 'chunking' | 'embedding' | 'storing' | 'completed' | 'failed'
export interface UploadJob { id: string; fileName: string; size: number; stage: UploadStage; progress: number; chunks: number; failedRemediationChunks: number; storedIncidents: number; error?: string }
export interface EvaluationPoint { step: number; label: string; correct: number; accepted: number; total: number; score: number; coverage: number; retrievalPrecision: number; failedFixAvoidance: number; memoryRecords: number }
export interface EvaluationCaseResult { incidentId: string; expectedAction: string; recommendedAction?: string | null; status: string; retrievedIds: string[]; relevantIds: string[]; method: string }
export interface EvaluationSummary { metrics: Array<{ name: string; withoutMemory: string; withMemory: string; improved: boolean; delta: number }>; progress: EvaluationPoint[]; completed: number; total: number; backend: 'hindsight' | 'sqlite' | 'mock'; bank?: string | null; methodology: string; cases: EvaluationCaseResult[] }
