import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Check, ExternalLink, ShieldAlert, X } from 'lucide-react'
import { useState } from 'react'
import { Link } from 'react-router-dom'
import { api } from '../api'
import { ConfirmationDialog, EmptyState, ErrorState, LoadingState, PageHeader, StatusBadge, WorkflowNotice } from '../components/ui'

export function ApprovalsPage() {
  const client = useQueryClient()
  const [reviewers, setReviewers] = useState<Record<string, string>>({})
  const [pendingDecision, setPendingDecision] = useState<{ id: string; approved: boolean } | null>(null)
  const { data, isLoading, isError } = useQuery({ queryKey: ['pending-approvals'], queryFn: () => api.getIncidents({ status: 'APPROVAL_REQUIRED' }) })
  const decision = useMutation({ mutationFn: ({ id, approved }: { id: string; approved: boolean }) => api.submitApproval(id, approved, reviewers[id]), onSuccess: () => { client.invalidateQueries({ queryKey: ['pending-approvals'] }); setPendingDecision(null) } })
  return <><PageHeader eyebrow="Policy control" title="Pending approvals" description="Review evidence for medium and high risk simulated actions. Decisions are bound to the incident and recommended action." />
    <WorkflowNotice type="approval">Approval authorizes one simulated remediation attempt. Independent service health and operation checks still determine recovery.</WorkflowNotice>
    <div className="mt-4">{isLoading ? <LoadingState /> : isError ? <ErrorState detail="The approval queue could not be retrieved. Try again." /> : !data?.length ? <EmptyState title="No approvals pending" detail="Medium and high risk recommendations will appear here." /> : <div className="grid gap-4 lg:grid-cols-2">{data.map((incident) => <ApprovalCard key={incident.incident_id} incidentId={incident.incident_id} reviewer={reviewers[incident.incident_id] ?? ''} onReviewer={(value) => setReviewers((current) => ({ ...current, [incident.incident_id]: value }))} onDecision={(approved) => setPendingDecision({ id: incident.incident_id, approved })} pending={decision.isPending} />)}</div>}</div>
    <ConfirmationDialog open={pendingDecision !== null} title={pendingDecision?.approved ? 'Approve remediation attempt?' : 'Reject remediation attempt?'} description={pendingDecision?.approved ? 'This authorizes one simulated attempt. Recovery still requires independent verification.' : 'The simulated action will not run and the incident will remain unresolved.'} confirmLabel={pendingDecision?.approved ? 'Approve attempt' : 'Reject action'} tone={pendingDecision?.approved ? 'primary' : 'danger'} busy={decision.isPending} onClose={() => setPendingDecision(null)} onConfirm={() => pendingDecision && decision.mutate(pendingDecision)}>{pendingDecision && <div className="rounded-md bg-slate-50 p-3"><p className="data-label">Decision record</p><p className="mt-1 font-mono text-xs font-semibold">{pendingDecision.id}</p><p className="mt-1 text-xs text-muted">Reviewer: {reviewers[pendingDecision.id]}</p></div>}</ConfirmationDialog>
  </>
}

function ApprovalCard({ incidentId, reviewer, onReviewer, onDecision, pending }: { incidentId: string; reviewer: string; onReviewer: (value: string) => void; onDecision: (approved: boolean) => void; pending: boolean }) {
  const { data } = useQuery({ queryKey: ['incident', incidentId], queryFn: () => api.getIncident(incidentId) })
  if (!data) return <div className="panel h-64 animate-pulse bg-slate-100" />
  return <article className="panel p-4"><div className="flex items-start justify-between"><div><p className="font-mono text-xs font-semibold text-navy-900">{incidentId}</p><p className="mt-1 text-xs text-muted">{data.incident.service} · {data.incident.error_code}</p></div><StatusBadge value={data.risk_level} /></div><div className="mt-3 rounded-md border border-purple-200 bg-[#F9F5FF] p-3"><div className="flex gap-2.5"><ShieldAlert className="shrink-0 text-memory" size={17} /><div><p className="font-mono text-xs font-semibold text-purple-950">{data.recommended_action}</p><p className="mt-1 text-xs leading-5 text-purple-800">Python policy requires approval for this {data.risk_level.toLowerCase()} action.</p></div></div></div><div className="mt-3"><p className="data-label">Supporting evidence</p><div className="mt-2 flex flex-wrap gap-1.5">{data.evidence.map((item) => <span key={item.incident_id} className="rounded border bg-slate-50 px-2 py-1 font-mono text-[10px] font-semibold">{item.incident_id} · {Math.round(item.similarity * 100)}%</span>)}</div></div><label className="mt-3 block"><span className="label">Reviewer name</span><input className="field" value={reviewer} onChange={(event) => onReviewer(event.target.value)} placeholder="Required for a decision" /></label><div className="mt-3 flex flex-wrap items-center gap-2"><button className="btn-danger" disabled={!reviewer || pending} onClick={() => onDecision(false)}><X size={15} />Reject</button><button className="btn-primary" disabled={!reviewer || pending} onClick={() => onDecision(true)}><Check size={15} />Approve attempt</button><Link to={`/incidents/${incidentId}`} className="ml-auto inline-flex items-center gap-1 text-xs font-semibold text-blue-700 hover:text-blue-800">Full workspace <ExternalLink size={12} /></Link></div></article>
}
