import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { ArrowDown, ArrowRight, ArrowUp, Database, FlaskConical, Info, Minus } from 'lucide-react'
import { api } from '../api'
import { ErrorState, LoadingState, PageHeader, StatusBadge } from '../components/ui'

export function EvaluationPage() {
  const client = useQueryClient()
  const refresh = useMutation({ mutationFn: () => api.refreshEvaluation(), onSuccess: () => client.invalidateQueries({ queryKey: ['evaluation'] }) })
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['evaluation'], queryFn: () => api.getEvaluation(), retry: 1, refetchInterval: 3000 })
  if (isLoading) return <LoadingState label="Running memory evaluation" />
  if (isError || !data) return <ErrorState title="Evaluation unavailable" detail={error instanceof Error ? error.message : 'Check the API and Hindsight connection.'} />
  const chart = data.progress.map((point, index) => ({ ...point, x: data.progress.length === 1 ? 0 : index * 100 / (data.progress.length - 1), y: 100 - point.score }))
  const backendLabel = data.backend === 'hindsight' ? 'Live Hindsight memory' : `${data.backend} development backend`
  return <><PageHeader eyebrow="Measured memory evaluation" title="Does memory actually improve the agent?" description="The same held-out incidents are rerun after every evidence or outcome checkpoint." />
    <div className={`mb-4 flex gap-2.5 rounded-md border px-3.5 py-2.5 text-[13px] leading-5 ${data.backend === 'hindsight' ? 'border-emerald-200 bg-emerald-50 text-emerald-900' : 'border-amber-200 bg-amber-50 text-amber-900'}`}><Database className="mt-0.5 shrink-0" size={16} /><p><strong>{backendLabel}.</strong> {data.bank ? `Bank: ${data.bank}. ` : ''}{data.methodology}</p></div>
    <div className="mb-4 flex gap-2.5 rounded-md border border-blue-200 bg-blue-50 px-3.5 py-2.5 text-[13px] leading-5 text-blue-900"><Info className="mt-0.5 shrink-0" size={16} /><p>The held-out labels are used only for scoring. They are never included in model prompts or memory records. A flat or falling line is preserved as a real result.</p></div>
    <div className="mb-4 flex items-center gap-3"><button className="btn-secondary" onClick={() => refresh.mutate()} disabled={refresh.isPending || data.evaluationStatus === 'running'}>Refresh metrics</button>{data.evaluationStatus === 'running' && <p role="status" className="text-sm text-muted">Evaluating Hindsight memory: {data.evaluatedCases ?? 0} of {data.total} cases. The last completed measurement stays visible.</p>}</div>
    {refresh.error && <p role="alert" className="mb-4 text-sm text-red-700">{refresh.error.message}</p>}
    {data.evaluationError && <p role="alert" className="mb-4 text-sm text-red-700">Evaluation needs attention: {data.evaluationError}</p>}
    <section className="panel overflow-hidden"><div className="panel-header"><div><p className="eyebrow">Before and current</p><h2 className="mt-1 font-bold text-navy-900">Measured performance</h2></div><FlaskConical className="text-blue-600" /></div><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-sm"><thead className="bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Metric</th><th className="px-5 py-3">Empty memory</th><th className="px-5 py-3">Change</th><th className="px-5 py-3">Current memory</th></tr></thead><tbody className="divide-y">{data.metrics.map((metric) => <tr key={metric.name}><td className="px-5 py-4 font-semibold">{metric.name}</td><td className="px-5 py-4 text-slate-500">{metric.withoutMemory}</td><td className={`px-5 py-4 font-semibold ${metric.delta > 0 ? 'text-emerald-700' : metric.delta < 0 ? 'text-red-700' : 'text-slate-500'}`}>{metric.delta > 0 ? <ArrowUp size={17} /> : metric.delta < 0 ? <ArrowDown size={17} /> : <Minus size={17} />}</td><td className="px-5 py-4 font-bold text-slate-800">{metric.withMemory}</td></tr>)}</tbody></table></div></section>
    <section className="panel mt-5 p-5"><div className="flex items-end justify-between"><div><p className="eyebrow">Learning curve</p><h2 className="section-title mt-1">Held-out action accuracy by checkpoint</h2></div><p className="text-sm font-bold text-blue-700">{data.progress.length} measured checkpoint{data.progress.length === 1 ? '' : 's'}</p></div><div className="mt-5 grid grid-cols-[36px_1fr] gap-3"><div className="flex flex-col justify-between pb-6 text-[10px] text-muted"><span>100%</span><span>50%</span><span>0%</span></div><div><svg viewBox="0 0 100 105" preserveAspectRatio="none" className="h-52 w-full overflow-visible" role="img" aria-label="Measured action accuracy by memory checkpoint"><line x1="0" y1="0" x2="100" y2="0" stroke="#e2e8f0" /><line x1="0" y1="50" x2="100" y2="50" stroke="#e2e8f0" /><line x1="0" y1="100" x2="100" y2="100" stroke="#cbd5e1" /><polyline fill="none" stroke="#2563eb" strokeWidth="2" vectorEffect="non-scaling-stroke" points={chart.map((point) => `${point.x},${point.y}`).join(' ')} />{chart.map((point) => <circle key={`${point.step}-${point.label}`} cx={point.x} cy={point.y} r="1.8" fill="#2563eb" vectorEffect="non-scaling-stroke" />)}</svg><div className="mt-1 flex justify-between text-[10px] text-muted"><span>{chart[0]?.label}</span><span>{chart.at(-1)?.label}</span></div></div></div><p className="mt-3 text-xs text-muted">Each point reruns all {data.total} held-out incidents against the memory available at that moment.</p></section>
    <section className="panel mt-5 overflow-hidden"><div className="panel-header"><div><p className="eyebrow">Evaluation evidence</p><h2 className="section-title mt-1">Latest per-case results</h2></div></div><div className="divide-y">{data.cases.map((item) => <article key={item.incidentId} className="grid min-w-0 gap-4 px-5 py-4 sm:grid-cols-2 xl:grid-cols-[minmax(180px,0.75fr)_minmax(220px,1.15fr)_minmax(220px,1.15fr)_auto] xl:items-center"><div className="min-w-0"><p className="font-mono text-xs font-semibold">{item.incidentId}</p><p className="mt-1 break-words text-xs leading-5 text-muted">{item.method.replaceAll('_', ' ')}</p></div><div className="min-w-0"><p className="text-xs text-muted">Expected</p><p className="mt-1 break-words font-mono text-sm font-semibold">{item.expectedAction}</p></div><div className="min-w-0"><p className="text-xs text-muted">Recommended</p><p className="mt-1 break-words font-mono text-sm font-semibold">{item.recommendedAction ?? 'Abstained'}</p></div><div className="flex min-w-0 flex-wrap items-center gap-2 sm:col-span-2 xl:col-span-1 xl:justify-end"><StatusBadge value={item.status} /><ArrowRight size={15} className="shrink-0 text-faint" /><span className="whitespace-nowrap text-xs text-muted">{item.retrievedIds.length} recalled</span></div></article>)}</div></section>
  </>
}
