import { useQuery } from '@tanstack/react-query'
import { ArrowRight, CheckCircle2, FlaskConical, Info } from 'lucide-react'
import { api } from '../api'
import { LoadingState, PageHeader, StatusBadge } from '../components/ui'

export function EvaluationPage() {
  const { data, isLoading } = useQuery({ queryKey: ['evaluation'], queryFn: () => api.getEvaluation() })
  if (isLoading || !data) return <LoadingState label="Loading evaluation results" />
  return <><PageHeader eyebrow="Memory evaluation" title="What changes when the agent remembers" description="The same investigator is measured with empty memory and with seeded historical evidence. Results come from six synthetic held-out cases." />
    <div className="mb-4 flex gap-2.5 rounded-md border border-blue-200 bg-blue-50 px-3.5 py-2.5 text-[13px] leading-5 text-blue-900"><Info className="mt-0.5 shrink-0" size={16} /><p><strong>Synthetic benchmark:</strong> these cases resemble the stored incident families. The comparison demonstrates workflow behavior and safety gates; it is not a production accuracy claim. Zero tool calls may indicate abstention or an approval pause.</p></div>
    <section className="panel overflow-hidden"><div className="panel-header"><div><p className="eyebrow">Before and after</p><h2 className="mt-1 font-bold text-navy-900">Memory-backed performance</h2></div><FlaskConical className="text-blue-600" /></div><div className="overflow-x-auto"><table className="w-full min-w-[660px] text-sm"><thead className="bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Metric</th><th className="px-5 py-3">Without memory</th><th className="px-5 py-3">Transition</th><th className="px-5 py-3">With Hindsight memory</th></tr></thead><tbody className="divide-y">{data.metrics.map((metric) => <tr key={metric.name}><td className="px-5 py-4 font-semibold">{metric.name}</td><td className="px-5 py-4 text-slate-500">{metric.withoutMemory}</td><td className="px-5 py-4"><ArrowRight className={metric.improved ? 'text-emerald-600' : 'text-slate-300'} size={18} /></td><td className={`px-5 py-4 font-bold ${metric.improved ? 'text-emerald-700' : 'text-slate-700'}`}>{metric.withMemory}</td></tr>)}</tbody></table></div></section>
    <section className="mt-5"><div className="mb-3"><p className="eyebrow">Safety challenges</p><h2 className="section-title mt-1">Abstention under uncertainty</h2></div><div className="panel grid divide-y md:grid-cols-3 md:divide-x md:divide-y-0">{data.challenges.map((challenge) => <article key={challenge.name} className="p-4"><div className="flex items-center justify-between"><CheckCircle2 className="text-[#15803D]" size={18} /><StatusBadge value={challenge.status} /></div><h3 className="mt-3 text-[13px] font-semibold">{challenge.name}</h3><p className="mt-1 text-xs leading-5 text-muted">{challenge.detail}</p></article>)}</div></section>
  </>
}
