import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { ArrowLeft, BrainCircuit, CheckCircle2, CircleDot, Database, Play, ShieldCheck, X } from 'lucide-react'
import { useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { api } from '../api'
import { LoadingState, OutcomeTimeline, StatusBadge, WorkflowNotice } from '../components/ui'

export function IncidentPage() {
  const { id = 'TEST-001' } = useParams()
  const client = useQueryClient()
  const [approvalOpen, setApprovalOpen] = useState(false)
  const [reviewer, setReviewer] = useState('')
  const { data, isLoading } = useQuery({ queryKey: ['incident', id], queryFn: () => api.getIncident(id) })
  const workflow = useMutation({ mutationFn: () => api.runWorkflow(id), onSuccess: (next) => client.setQueryData(['incident', id], next) })
  const approval = useMutation({ mutationFn: (approved: boolean) => api.submitApproval(id, approved, reviewer), onSuccess: (next) => { client.setQueryData(['incident', id], next); setApprovalOpen(false) } })
  if (isLoading || !data) return <LoadingState label="Building incident workspace" />
  const current = workflow.data ?? data
  return <><Link to="/incidents" className="mb-4 inline-flex items-center gap-2 text-sm font-semibold text-slate-600"><ArrowLeft size={16} />Back to incidents</Link>
    <div className="mb-4 flex flex-col justify-between gap-3 lg:flex-row lg:items-start"><div><div className="flex flex-wrap items-center gap-2"><h1 className="font-mono text-xl font-semibold text-navy-900">{current.incident.incident_id}</h1><StatusBadge value={current.incident.severity} /><StatusBadge value={current.workflow_status} /></div><p className="mt-1.5 text-[13px] text-muted">{current.incident.service} · {current.incident.environment} · <span className="font-mono">{current.incident.error_code}</span> · {new Date(current.incident.occurred_at).toLocaleString()}</p></div><div className="flex gap-2">{current.policy_status === 'HUMAN_APPROVAL_REQUIRED' && <button className="btn-primary" onClick={() => setApprovalOpen(true)}><ShieldCheck size={16} />Review action</button>}{current.policy_status === 'ALLOWED' && !current.verification && <button className="btn-primary" onClick={() => workflow.mutate()} disabled={workflow.isPending}><Play size={16} />Run simulated workflow</button>}</div></div>
    <WorkflowNotice type="simulation">All remediation and verification activity on this page is simulated. Tool acknowledgement and verified recovery are displayed separately.</WorkflowNotice>
    <div className="mt-4 grid gap-4 xl:grid-cols-[1.25fr_.75fr]"><div className="space-y-4"><section className="panel p-4"><p className="eyebrow">Incident context</p><h2 className="section-title mt-1">Symptoms and identifiers</h2><div className="mt-3 flex flex-wrap gap-1.5">{current.incident.symptoms.map((symptom) => <span key={symptom} className="rounded-md border bg-slate-50 px-2.5 py-1.5 text-xs text-navy-700">{symptom}</span>)}</div><dl className="mt-4 grid gap-x-5 gap-y-3 border-t pt-3 sm:grid-cols-2"><div><dt className="data-label">Error message</dt><dd className="mt-1 text-xs text-ink">{current.incident.error_message ?? 'No message supplied'}</dd></div><div><dt className="data-label">Affected reference</dt><dd className="mt-1 font-mono text-xs text-ink">{current.incident.transaction_id ?? current.incident.job_id ?? current.incident.customer_id ?? 'None supplied'}</dd></div></dl>{current.incident.recent_change && <p className="mt-3 rounded-md border border-amber-200 bg-[#FFFBEB] p-3 text-xs text-amber-900"><strong>Recent change:</strong> {current.incident.recent_change}</p>}</section>
      <section className="panel"><div className="panel-header"><div><p className="eyebrow">Investigation</p><h2 className="section-title mt-1">Recommendation and evidence</h2></div><BrainCircuit className="text-memory" size={19} /></div><div className="space-y-4 p-4"><div className="grid gap-4 sm:grid-cols-2"><div><p className="data-label">Likely root cause</p><p className="mt-1 text-[13px] font-semibold text-ink">{current.likely_root_cause}</p></div><div><p className="data-label">Recommended action</p><p className="mt-1 font-mono text-xs font-semibold text-blue-700">{current.recommended_action}</p></div></div><div><div className="mb-1.5 flex justify-between text-xs"><span className="font-medium text-muted">Historical confidence</span><span className="font-semibold">{(current.confidence * 100).toFixed(1)}%</span></div><div className="h-1.5 rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-600" style={{ width: `${current.confidence * 100}%` }} /></div></div><p className="text-[13px] leading-5 text-muted">{current.reasoning}</p><dl className="grid gap-3 border-y py-3 sm:grid-cols-2"><div><dt className="data-label">Investigation method</dt><dd className="mt-1 text-xs text-ink">{current.investigation_method.replaceAll('_', ' ')}</dd></div><div><dt className="data-label">Model</dt><dd className="mt-1 font-mono text-xs text-ink">{current.model_name ?? 'Rules only'}</dd></div></dl><div className="flex flex-wrap gap-2"><StatusBadge value={current.risk_level} label={`${current.risk_level.toLowerCase()} action risk`} /><StatusBadge value={current.policy_status} /></div>{current.failed_actions_avoided.length > 0 && <div className="rounded-md border border-red-200 bg-[#FEF3F2] p-3"><p className="data-label text-[#B42318]">Failed fix avoided</p><p className="mt-1 font-mono text-xs font-semibold text-red-900">{current.failed_actions_avoided.join(', ')}</p></div>}</div></section>
      <section className="panel"><div className="panel-header"><div><p className="eyebrow">Historical evidence</p><h2 className="mt-1 font-bold text-navy-900">Successful and failed remediation</h2></div><Database className="text-purple-600" /></div><div className="grid gap-4 p-5 lg:grid-cols-2">{current.evidence.map((item) => <article key={item.incident_id} className="rounded-xl border p-4"><div className="mb-4 flex items-start justify-between"><div><p className="font-mono text-sm font-bold">{item.incident_id}</p><p className="text-xs text-slate-500">{item.root_cause}</p></div><span className="text-xs font-bold text-purple-700">{Math.round(item.similarity * 100)}% match</span></div><OutcomeTimeline outcomes={item.outcomes} /></article>)}</div></section></div>
      <div className="space-y-5"><section className="panel p-5"><p className="eyebrow">Response timeline</p><h2 className="mt-1 font-bold text-navy-900">Current incident</h2><ol className="mt-5 space-y-4">{[{ label: 'Incident received', done: true }, { label: 'Hindsight evidence recalled', done: true }, { label: 'Recommendation validated', done: true }, { label: current.policy_status === 'ALLOWED' ? 'Policy allowed action' : 'Human approval required', done: current.policy_status === 'ALLOWED' }, { label: 'Simulated remediation', done: !!current.verification }, { label: 'Operation reprocessed', done: !!current.verification }, { label: 'Independent verification', done: !!current.verification }, { label: 'Outcome written to memory', done: current.memory_stored }].map((step) => <li key={step.label} className="flex items-center gap-3"><span className={`grid h-7 w-7 place-items-center rounded-full ${step.done ? 'bg-emerald-100 text-emerald-700' : 'bg-slate-100 text-slate-400'}`}>{step.done ? <CheckCircle2 size={16} /> : <CircleDot size={15} />}</span><span className={`text-sm ${step.done ? 'font-semibold text-slate-800' : 'text-slate-500'}`}>{step.label}</span></li>)}</ol></section>
      {current.verification && <section className="panel p-4"><p className="eyebrow">Independent verification</p><h2 className="section-title mt-1">Observed state</h2><dl className="mt-3 divide-y rounded-md border"><div className="flex justify-between px-3 py-2.5 text-xs"><dt>Tool acknowledgement</dt><dd><StatusBadge value={current.tool_acknowledgement ?? 'FAILED'} /></dd></div><div className="flex justify-between px-3 py-2.5 text-xs"><dt>Service health</dt><dd className="font-semibold">{current.verification.service_healthy ? 'Healthy' : 'Unhealthy'}</dd></div><div className="flex justify-between px-3 py-2.5 text-xs"><dt>Affected operation</dt><dd className="font-semibold">{current.verification.operation_recovered ? 'Recovered' : 'Not recovered'}</dd></div><div className="flex justify-between px-3 py-2.5 text-xs font-semibold"><dt>Overall result</dt><dd><StatusBadge value={current.verification.result} /></dd></div></dl><p className="mt-2 text-[11px] leading-4 text-muted">The tool acknowledgement is recorded separately and does not establish recovery.</p>{current.memory_stored && <div className="mt-3"><WorkflowNotice type="memory"><strong>Outcome stored in memory.</strong> Later investigations can retrieve this verified result.</WorkflowNotice></div>}</section>}</div></div>
    {approvalOpen && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4"><div role="dialog" aria-modal="true" aria-labelledby="approval-title" className="w-full max-w-lg rounded-xl bg-white shadow-2xl"><div className="flex items-start justify-between border-b p-5"><div><p className="eyebrow">Bound policy approval</p><h2 id="approval-title" className="mt-1 text-lg font-bold">Authorize simulated attempt</h2></div><button onClick={() => setApprovalOpen(false)} className="rounded p-1 text-slate-500" aria-label="Close"><X /></button></div><div className="space-y-4 p-5"><WorkflowNotice type="approval">Approval authorizes the attempt. It does not mean the action succeeded or that the service recovered.</WorkflowNotice><div className="rounded-lg bg-slate-50 p-4"><p className="font-mono text-sm font-bold">{current.recommended_action}</p><div className="mt-2"><StatusBadge value={current.risk_level} /></div><p className="mt-3 text-sm text-slate-600">Supported by {current.evidence.map((item) => item.incident_id).join(', ')}.</p></div><label><span className="label">Reviewer name</span><input className="field" value={reviewer} onChange={(event) => setReviewer(event.target.value)} placeholder="Enter your name" /></label></div><div className="flex justify-end gap-2 border-t p-5"><button className="btn-secondary text-red-700" disabled={!reviewer || approval.isPending} onClick={() => approval.mutate(false)}>Reject</button><button className="btn-primary" disabled={!reviewer || approval.isPending} onClick={() => approval.mutate(true)}>Approve simulated action</button></div></div></div>}
  </>
}
