import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { ArrowRight, RotateCcw, Search } from 'lucide-react'
import { useState } from 'react'
import { Link } from 'react-router-dom'
import { api } from '../api'
import { EmptyState, ErrorState, LoadingState, PageHeader, StatusBadge } from '../components/ui'

export function IncidentsPage() {
  const queryClient = useQueryClient()
  const [query, setQuery] = useState('')
  const [status, setStatus] = useState('')
  const [severity, setSeverity] = useState('')
  const [service, setService] = useState('')
  const { data, isLoading, isError } = useQuery({ queryKey: ['incidents', query, status, severity, service], queryFn: () => api.getIncidents({ query, status, severity, service }) })
  const resetDemo = useMutation({ mutationFn: () => api.resetDemo(), onSuccess: () => queryClient.invalidateQueries() })
  return <><PageHeader eyebrow="Incident queue" title="Production incidents" description="Open an incident workspace to review historical evidence, policy decisions, simulated actions, and independent recovery checks." action={<button type="button" className="btn-secondary" onClick={() => resetDemo.mutate()} disabled={resetDemo.isPending}><RotateCcw size={15} />Reset demo</button>} />
    <div className="panel mb-4 flex flex-col gap-2.5 p-3 md:flex-row"><label className="min-w-0 flex-1"><span className="sr-only">Search incidents</span><div className="relative"><Search className="absolute left-3 top-2.5 text-faint" size={16} /><input className="field pl-9" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search ID, service, or error code" /></div></label><select className="field md:w-44" aria-label="Filter status" value={status} onChange={(event) => setStatus(event.target.value)}><option value="">All statuses</option><option value="INVESTIGATING">Investigating</option><option value="APPROVAL_REQUIRED">Approval required</option><option value="RESOLVED">Resolved</option></select><select className="field md:w-36" aria-label="Filter severity" value={severity} onChange={(event) => setSeverity(event.target.value)}><option value="">All severities</option><option>CRITICAL</option><option>HIGH</option><option>MEDIUM</option><option>LOW</option></select><select className="field md:w-52" aria-label="Filter service" value={service} onChange={(event) => setService(event.target.value)}><option value="">All services</option>{['customer-service','payment-service','database-service','queue-service','catalog-service','fulfillment-service'].map((name) => <option key={name}>{name}</option>)}</select><button className="btn-secondary" onClick={() => { setQuery(''); setStatus(''); setSeverity(''); setService('') }} aria-label="Reset filters"><RotateCcw size={15} />Clear filters</button></div>
    {isLoading ? <LoadingState /> : isError ? <ErrorState detail="The incident list could not be retrieved. Try again." /> : !data?.length ? <EmptyState title="No incidents yet" detail="Upload incident history to populate the learning demonstration." /> : <div className="panel overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[820px] text-left text-[13px]"><thead className="border-b bg-slate-50 text-[11px] font-semibold uppercase tracking-[0.06em] text-muted"><tr><th className="px-4 py-2.5">Incident</th><th className="px-4 py-2.5">Service</th><th className="px-4 py-2.5">Severity</th><th className="px-4 py-2.5">Environment</th><th className="px-4 py-2.5">Status</th><th className="px-4 py-2.5">Occurred</th><th className="px-4 py-2.5" /></tr></thead><tbody className="divide-y">{data.map((incident) => <tr key={incident.incident_id} className="transition-colors duration-150 hover:bg-slate-50"><td className="px-4 py-3"><p className="font-mono text-xs font-semibold text-navy-900">{incident.incident_id}</p><p className="mt-0.5 font-mono text-[11px] text-muted">{incident.error_code}</p></td><td className="px-4 py-3 font-medium">{incident.service}</td><td className="px-4 py-3"><StatusBadge value={incident.severity} label={`${incident.severity.toLowerCase()} severity`} /></td><td className="px-4 py-3 capitalize text-muted">{incident.environment}</td><td className="px-4 py-3"><StatusBadge value={incident.status} /></td><td className="px-4 py-3 text-muted">{new Date(incident.occurred_at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</td><td className="px-4 py-3"><Link to={`/incidents/${incident.incident_id}`} className="inline-flex items-center gap-1 font-semibold text-blue-700 hover:text-blue-800">Open <ArrowRight size={14} /></Link></td></tr>)}</tbody></table></div></div>}
  </>
}
