import { useQuery } from '@tanstack/react-query'
import { ChevronDown, Database, FileJson, Search } from 'lucide-react'
import { useState } from 'react'
import { Link } from 'react-router-dom'
import { api } from '../api'
import { EmptyState, ErrorState, LoadingState, OutcomeTimeline, PageHeader, StatusBadge, WorkflowNotice } from '../components/ui'

export function MemoryPage() {
  const [query, setQuery] = useState('')
  const [result, setResult] = useState('')
  const [service, setService] = useState('')
  const [expanded, setExpanded] = useState<string | null>('INC-101')
  const { data, isLoading, isError } = useQuery({ queryKey: ['memory', query, result, service], queryFn: () => api.searchMemory({ query, result, service }) })
  const visible = data
  return <><PageHeader eyebrow="Hindsight memory" title="Memory explorer" description="Search complete incident records and inspect the ordered evidence that supports or blocks future recommendations." action={<Link to="/memory/upload" className="btn-primary"><FileJson size={17} />Upload incident records</Link>} />
    <WorkflowNotice type="memory"><strong>Hindsight’s role:</strong> searchable chunks help recall relevant history. Complete validated incident records remain the source of truth for ordered outcomes and evidence IDs.</WorkflowNotice>
    <div className="panel my-4 flex flex-col gap-2.5 p-3 md:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-2.5 text-faint" size={16} /><input className="field pl-9" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search incident, service, root cause, or action" /></div><select className="field md:w-48" aria-label="Filter outcome" value={result} onChange={(event) => setResult(event.target.value)}><option value="">All evidence</option><option value="SUCCESS">Successful fixes</option><option value="FAILED">Failed fixes</option><option value="PARTIAL">Partial recoveries</option></select><select className="field md:w-52" aria-label="Filter memory service" value={service} onChange={(event) => setService(event.target.value)}><option value="">All services</option>{['customer-service','payment-service','database-service','queue-service','catalog-service','fulfillment-service'].map((name) => <option key={name}>{name}</option>)}</select></div>
    {isLoading ? <LoadingState label="Searching Hindsight memory" /> : isError ? <ErrorState detail="Hindsight memory could not be searched. Try again." /> : !visible?.length ? <EmptyState title="No memory found" detail="Try another query or upload incident records." /> : <div className="space-y-2">{visible.map((memory) => { const open = expanded === memory.incident.incident_id; return <article key={memory.incident.incident_id} className="panel overflow-hidden"><button onClick={() => setExpanded(open ? null : memory.incident.incident_id)} className="flex w-full items-center gap-3 px-4 py-3 text-left transition-colors duration-150 hover:bg-slate-50" aria-expanded={open}><span className="rounded-md bg-[#F9F5FF] p-2 text-memory"><Database size={16} /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-mono text-xs font-semibold">{memory.related_incident_id ?? memory.incident.incident_id}</p><StatusBadge value={memory.workflow_status ?? memory.final_outcome ?? 'INVESTIGATING'} /></div><p className="mt-0.5 truncate text-xs text-muted">{memory.incident.service} · {memory.root_cause}</p></div><div className="hidden text-right sm:block"><p className="text-xs font-medium text-muted">{memory.outcomes.length} ordered outcomes</p><p className="text-[10px] text-faint">{memory.source_filename}</p></div><ChevronDown size={16} className={`text-faint transition-transform duration-150 ${open ? 'rotate-180' : ''}`} /></button>{open && <div className="grid gap-5 memory-expanded border-t p-4 lg:grid-cols-[1fr_280px]"><div><p className="eyebrow mb-3">Ordered outcome timeline</p><OutcomeTimeline outcomes={memory.outcomes} />{memory.final_resolution && <p className="mt-3 text-sm text-muted">{memory.final_resolution}</p>}{memory.record_kind === 'observation' && <p className="mt-2 text-xs text-muted">Investigation observation. No remediation outcome is claimed.</p>}</div><aside className="rounded-md border bg-white p-4"><p className="eyebrow">Source and chunks</p><p className="mt-2 flex items-center gap-2 text-xs font-semibold"><FileJson size={14} />{memory.source_filename}</p><div className="mt-3 space-y-1.5">{memory.chunk_refs?.map((chunk) => <div key={chunk} className="rounded bg-[#F9F5FF] px-2.5 py-1.5 font-mono text-[10px] text-memory">{chunk}</div>)}</div><p className="mt-3 text-xs leading-5 text-muted">Chunks improve search. The complete record supplies the validated action order shown here.</p></aside></div>}</article> })}</div>}
  </>
}
