import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { ArrowRight, CheckCircle2, Clock3, Database, RotateCcw, ShieldAlert, Sparkles } from 'lucide-react'
import { Link } from 'react-router-dom'
import { api } from '../api'
import { LoadingState, PageHeader, StatusBadge } from '../components/ui'

export function OverviewPage() {
  const queryClient = useQueryClient()
  const { data, isLoading } = useQuery({ queryKey: ['overview'], queryFn: () => api.getOverview() })
  const reset = useMutation({ mutationFn: () => api.resetDemo(), onSuccess: () => queryClient.invalidateQueries() })
  if (isLoading || !data) return <LoadingState />
  const stats = [
    { label: 'Active incidents', value: data.active, icon: ShieldAlert, tone: 'text-[#dc5d50]', path: '/incidents' },
    { label: 'Awaiting approval', value: data.pendingApprovals, icon: Clock3, tone: 'text-[#c48732]', path: '/approvals' },
    { label: 'Resolved', value: data.resolved, icon: CheckCircle2, tone: 'text-[#259474]', path: '/incidents' },
    { label: 'Memory records', value: data.memoryRecords, icon: Database, tone: 'text-[#6579bb]', path: '/memory' },
  ]
  return <>
    <PageHeader eyebrow="Command center" title="Incident response, in focus." description="The signals that matter, and the next action to take." action={<div className="flex flex-wrap gap-2"><button type="button" className="btn-secondary" onClick={() => reset.mutate()} disabled={reset.isPending}><RotateCcw size={15} />Reset demo</button><Link to="/memory/upload" className="btn-primary"><Sparkles size={16} />Load evidence</Link></div>} />

    <section className="mt-12" aria-label="Operations snapshot"><div className="section-heading"><div><p className="eyebrow">Today's snapshot</p><h2 className="section-title mt-1">At a glance</h2></div><span className="text-xs text-muted">Live workspace data</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{stats.map(({ label, value, icon: Icon, tone, path }) => <Link key={label} to={path} className="metric-card group"><div className="flex items-center justify-between"><span className="text-[13px] font-medium text-muted">{label}</span><Icon size={19} className={tone} strokeWidth={1.8} /></div><div className="mt-7 flex items-end justify-between"><strong className="text-[34px] font-semibold leading-none tracking-[-0.05em] text-ink tabular-nums">{value}</strong><ArrowRight size={16} className="text-faint transition-transform group-hover:translate-x-1" /></div></Link>)}</div></section>
    <div className="mt-10 grid gap-5 xl:grid-cols-[minmax(0,1.65fr)_minmax(280px,0.75fr)]"><section className="panel overflow-hidden"><div className="panel-header"><div><p className="eyebrow">Response queue</p><h2 className="section-title mt-1">Recent incidents</h2></div><Link to="/incidents" className="subtle-link">View all <ArrowRight size={15} /></Link></div>{data.recent.length ? <div className="divide-y divide-line">{data.recent.slice(0, 6).map((incident) => <Link key={incident.incident_id} to={`/incidents/${incident.incident_id}`} className="incident-row group"><span className={`severity-marker ${incident.severity === 'HIGH' || incident.severity === 'CRITICAL' ? 'bg-[#e16a5e]' : 'bg-[#d8a352]'}`} /><div className="min-w-0 flex-1"><p className="truncate text-[13px] font-semibold text-ink">{incident.service}</p><p className="mt-1 truncate text-xs text-muted">{incident.incident_id} <span className="mx-1.5 text-faint">·</span> {incident.error_code}</p></div><StatusBadge value={incident.status} /><ArrowRight size={16} className="hidden text-faint transition-transform group-hover:translate-x-1 sm:block" /></Link>)}</div> : <p className="p-6 text-sm text-muted">No incidents in the queue.</p>}</section><div className="space-y-5"><section className="panel p-6"><div className="flex items-center justify-between"><p className="eyebrow">Learning progress</p><span className="text-sm font-semibold tabular-nums text-ink">{data.learningScore.toFixed(0)}%</span></div><h2 className="section-title mt-3">Better with every resolution.</h2><p className="mt-2 text-[13px] leading-6 text-muted">{data.learningCompleted} of {data.learningTotal} benchmark workflows completed with verified outcomes.</p><div className="mt-6 h-2 overflow-hidden rounded-full bg-[#514760]"><div className="h-full rounded-full bg-[#377e6d] transition-all" style={{ width: `${data.learningScore}%` }} /></div><Link to="/evaluation" className="subtle-link mt-5">Explore evaluation <ArrowRight size={15} /></Link></section><section className="panel p-6"><p className="eyebrow">Next step</p><h2 className="section-title mt-3">Turn history into context.</h2><p className="mt-2 text-[13px] leading-6 text-muted">Add past incident records so recommendations can draw on outcomes your team has already seen.</p><Link to="/memory/upload" className="btn-secondary mt-5">Add incident records <ArrowRight size={15} /></Link></section></div></div>
  </>
}
