import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { ArrowRight, BrainCircuit, CheckCircle2, Clock3, Database, RotateCcw, ShieldAlert, Sparkles } from 'lucide-react'
import { Link } from 'react-router-dom'
import { api } from '../api'
import { LoadingState, PageHeader, StatCard, StatusBadge, WorkflowNotice } from '../components/ui'

export function OverviewPage() {
  const queryClient = useQueryClient()
  const { data, isLoading } = useQuery({ queryKey: ['overview'], queryFn: () => api.getOverview() })
  const reset = useMutation({ mutationFn: () => api.resetDemo(), onSuccess: () => queryClient.invalidateQueries() })
  if (isLoading || !data) return <LoadingState />
  return <><PageHeader eyebrow="Operations overview" title="See what memory changes during an incident" description="Track active response work, approval gates, verified recovery, and the historical evidence used for every recommendation." action={<div className="flex gap-2"><button type="button" className="btn-secondary" onClick={() => reset.mutate()} disabled={reset.isPending}><RotateCcw size={16} />Reset demo</button><Link to="/memory/upload" className="btn-primary"><Sparkles size={17} />Load evidence</Link></div>} />
    <WorkflowNotice type="simulation"><strong>Safe demonstration:</strong> remediation, reprocessing, and system observations shown in this console are simulated. Approval authorizes an attempt; verification establishes recovery.</WorkflowNotice>
    <div className="panel mt-4 grid overflow-hidden sm:grid-cols-2 xl:grid-cols-5"><StatCard label="Active incidents" value={data.active} hint="Across production services" icon={ShieldAlert} /><StatCard label="Resolved" value={data.resolved} hint="Verified service and operation" icon={CheckCircle2} tone="green" /><StatCard label="Pending approvals" value={data.pendingApprovals} hint="Medium and high risk" icon={Clock3} tone="amber" /><StatCard label="Memory records" value={data.memoryRecords} hint="Complete incident histories" icon={Database} tone="purple" /><StatCard label="Failed fixes avoided" value={data.failedFixesAvoided} hint="Preserved as negative evidence" icon={BrainCircuit} tone="blue" /></div>
    <section className="panel mt-4 p-4"><div className="flex flex-wrap items-end justify-between gap-2"><div><p className="eyebrow">Live learning checkpoint</p><h2 className="section-title mt-1">{data.learningCompleted} of {data.learningTotal} incident workflows completed</h2></div><Link to="/evaluation" className="text-sm font-semibold text-blue-700">Open learning curve <ArrowRight className="inline" size={14} /></Link></div><div className="mt-3 h-3 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-gradient-to-r from-blue-600 to-purple-600 transition-all" style={{ width: `${data.learningScore}%` }} /></div><div className="mt-2 flex justify-between text-xs text-muted"><span>Verified benchmark progress</span><strong className="text-navy-900">{data.learningScore.toFixed(1)}%</strong></div></section>
    <div className="mt-6 grid gap-6 xl:grid-cols-[1.5fr_1fr]"><section className="panel"><div className="panel-header"><div><p className="eyebrow">Recent activity</p><h2 className="mt-1 font-bold text-navy-900">Incident queue</h2></div><Link to="/incidents" className="text-sm font-semibold text-blue-700">View all</Link></div><div className="divide-y">{data.recent.map((incident) => <Link key={incident.incident_id} to={`/incidents/${incident.incident_id}`} className="flex items-center gap-4 px-5 py-4 hover:bg-slate-50"><span className={`h-2.5 w-2.5 rounded-full ${incident.severity === 'HIGH' || incident.severity === 'CRITICAL' ? 'bg-red-500' : 'bg-amber-500'}`} /><div className="min-w-0 flex-1"><p className="font-mono text-sm font-semibold">{incident.incident_id}</p><p className="truncate text-xs text-slate-500">{incident.service} · {incident.error_code}</p></div><StatusBadge value={incident.status} /><ArrowRight size={16} className="text-slate-400" /></Link>)}</div></section>
      <section className="panel p-5"><p className="eyebrow">Memory feedback loop</p><h2 className="section-title mt-1">How evidence returns to the system</h2><ol className="mt-4 border-l border-line">{['Upload and validate incident records', 'Retain complete records and searchable chunks', 'Recall successful and failed evidence', 'Recommend and evaluate policy', 'Verify recovery and write the outcome'].map((step, index) => <li key={step} className="relative pb-4 pl-5 last:pb-0"><span className="absolute -left-2 grid h-4 w-4 place-items-center rounded-full bg-navy-800 text-[9px] font-semibold text-white">{index + 1}</span><p className="text-[13px] font-medium text-ink">{step}</p><p className="mt-0.5 text-[11px] text-muted">{index === 2 ? 'Hindsight recall supplies the evidence.' : 'Recorded workflow stage'}</p></li>)}</ol><Link to="/memory/upload" className="btn-secondary mt-5 w-full">Open memory ingestion <ArrowRight size={15} /></Link></section></div></>
}
